name: 'YC API Gateway Deploy'
description: 'GitHub Action to deploy API Gateway to Yandex Cloud'
author: 'Andrei Khaliullin'
inputs:
  yc-sa-json-credentials:
    required: false
    description: 'JSON containing authorized key for Service Account.
      Either this or `yc-iam-token` or `yc-sa-id` should be provided.
      More info https://cloud.yandex.ru/docs/container-registry/operations/authentication#sa-json'
  yc-iam-token:
    required: false
    description: 'IAM token for Yandex Cloud. 
      Either this or `yc-sa-json-credentials` or `yc-sa-id` should be provided.
      More info https://yandex.cloud/ru/docs/iam/concepts/authorization/iam-token'
  yc-sa-id:
    required: false
    description: 'Service Account ID. Will be uses to exchange GitHub token to Yandex Cloud token.
      Either this or `yc-iam-token` or `yc-sa-json-credentials` should be provided.
      More info https://yandex.cloud/ru/docs/iam/concepts/workload-identity'
  gateway-name:
    required: true
    description: 'API Gateway name'
  folder-id:
    required: true
    description: 'Folder ID'
  spec:
    required: false
    description: "YAML or JSON specification of API Gateway. Either spec or spec-file must be provided"
  spec-file:
    required: false
    description: "Path to file with YAML or JSON specification of API Gateway. Either spec or spec-file must be provided"
outputs:
  id:
    description: 'Id of API Gateway'
  domain:
    description: 'Domain of API Gateway'
branding:
  color: blue
  icon: upload-cloud
runs:
  using: 'node20'
  main: 'dist/index.js'
